### ISSUE TITLE
Jipster version 4.11.1 problem

### ISSUE THREAD

**Issue by radni1234** [moifort/generator-jhipster-google-maps#8]
Jipster version 4.11.1

Composing JHipster configuration with module google-maps
WARNING! DEPRECATED! The JHipster module sub-generator is deprecated.
WARNING! Please import the generator-base.js using commonJS require or ES2015 import.
WARNING! See http://www.jhipster.tech/modules/creating-a-module for more details.

Reading the JHipster project configuration for your module

Unable to find bower.json. Reference to bower dependency (name: angular-google-maps, version:2.2.1) not added.

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.debug is not a function
    at Object.addBowerDependency (C:\Users\hp-pc\jhipster2\node_modules\generator-jhipster\generators\generator-base.js:542:18)
    at child.writing (C:\Users\hp-pc\jhipster2\node_modules\generator-jhipster-google-maps\generators\app\index.js:64:22)
    at C:\Users\hp-pc\jhipster2\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by codemonkeybr** [comment]
Im having the same issue with 4.13.3 of jhipster.... did got a workaround @radni1234 ?

**Comment by pascalgrimaud** [comment]
simply because this module is not maintained anymore... sorry guys

But feel free to take the lead and do the change to make it working with Angular and React !
